<!-- Web Improvement Team Header File -->
<!--STOPINDEX-->
<TABLE BGCOLOR="#0000FF" BORDER=0 CELLPADDING=0 CELLSPACING=0 SUMMARY="Main display table">
<TR valign="middle">

<!-- CELL 1, Containing SLAC & BaBar links -->
<TD WIDTH=118 HEIGHT=72 ALIGN=LEFT>
<!-- SLAC, PEP2 -->
 <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=1 SUMMARY="SLAC and PEPII table">
 <TR>
 <TD BGCOLOR="#0000FF" WIDTH=118>
  <TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=118 SUMMARY="SLAC and PEPII table">
  <TR BGCOLOR="#C6DEDE" ALIGN="CENTER">
  <TD WIDTH=52 BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/detailed.html">SLAC</A></TD>
  <TD WIDTH=52 BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/accel/pepii/home.html">PEP-II</A></TD></TR>
  <TR BGCOLOR="#FFFFFF" ALIGN=CENTER><TD COLSPAN="2" BGCOLOR="#FFFFFF" WIDTH=118><A HREF="/BFROOT/"><STRONG>BABAR</STRONG></A></TD></TR>
  <TR BGCOLOR="#C6DEDE" ALIGN=CENTER><TD COLSPAN="2" BGCOLOR="#C6DEDE"  WIDTH=118>
  <A HREF="http://www.slac.stanford.edu/BFROOT/www/.wit_root/slac.html"><small><STRONG>SLAC</STRONG></small></A><FONT color=red><small>&#60;-&#62;</small></FONT><A HREF="http://hepunx.rl.ac.uk/BFROOT/www/.wit_root/ral.html"><small><STRONG>RAL</STRONG></small></A>
   </TD></TR>
  </TABLE>
 </TD>
 </TR>
 </TABLE>
</TD> 
<!-- /CELL1 -->

<!-- CELL 2, Containing BaBar logo -->
<TD BGCOLOR="#0000FF">
 <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 SUMMARY="BaBar local">
 <TR>
 <TD BGCOLOR="#0000FF">
  <TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 SUMMARY="BaBar local">
  <TR BGCOLOR="#0000FF">
  <TD>
  <A HREF="/BFROOT/BABAR.html"><IMG SRC="/BFROOT/www/Images/BABARTM.gif" WIDTH=49 HEIGHT=72 ALT="Babar logo"></A>
  </TD>
  </TR>
  </TABLE>
 </TD>
 </TR>
 </TABLE>
</TD>
<!-- /CELL 2 -->

<!-- CELL 3, Containing the top navigation bar -->
<TD WIDTH="100%" ALIGN=CENTER>
 <TABLE BORDER=0 CELLSPACING=1 CELLPADDING=3 SUMMARY="Top Navigation Bar">
 <TR>
 <TD BGCOLOR="#0000FF" WIDTH="100%" ALIGN=CENTER>
  <TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 SUMMARY="Top Navigation Bar" ALIGN=CENTER >
  <TR BGCOLOR="#C6DEDE" VALIGN=TOP ALIGN=CENTER>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www.hep.net/">HEPIC</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/esh/">E,S &amp; H</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/accel/pepii/db.htm">Databases</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://pdg.lbl.gov/">PDG</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/spires/hep/">HEP preprints</A></TH>
  </TR>
  <TR BGCOLOR="#FFFFFF" VALIGN=MIDDLE ALIGN=CENTER>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/www/Organization/index.html">Organization</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/www/Detector/Detector.html">Detector</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/www/Computing/index.html">Computing</A></TH>
  <TH BGCOLOR="#FFFFCC"><A HREF="/BFROOT/www/Physics/Physics.html">Physics</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/www/doc/">Documentation</A></TH>
  </TR>
  <TR BGCOLOR="#C6DEDE" VALIGN=BOTTOM ALIGN=CENTER>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www-group.slac.stanford.edu/babar/find/peoples.aspx">Personnel</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://www.slac.stanford.edu/babar-pro-new/search.pl">Glossary</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/sitemap.html">Sitemap</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="/BFROOT/www/Babar_search.html">Search</A></TH>
  <TH BGCOLOR="#C6DEDE"><A HREF="http://babar-hn.slac.stanford.edu:5090/HyperNews/index">Hypernews</A></TH>
  </TR>
  </TABLE>
 </TD>
 </TR>
 </TABLE>
</TD>
<!-- /CELL3 -->

</TR>
</TABLE> <!-- END TOP TABLE -->

<TABLE WIDTH="100%" BORDER=0  CELLPADDING=0 CELLSPACING=0 SUMMARY="Side navigation and information">
<TR VALIGN="top">
<TD WIDTH="118" ALIGN="left" VALIGN="top" BGCOLOR="#FFFFFF">

 <TABLE WIDTH=118 BORDER=0 CELLSPACING=0 CELLPADDING=0 BGCOLOR="#000000" SUMMARY="Side navigation and information">
 <!-- Left Strip -->
 <TR valign="middle" BGCOLOR="#0000FF">
<TD BGCOLOR="#FFFFFF">
<TABLE WIDTH=118 BORDER=0 CELLPADDING=0 CELLSPACING=0 SUMMARY="unwrap">
<TR valign="middle"><TD ALIGN=CENTER BGCOLOR="#0000FF">
<A HREF="http://www.slac.stanford.edu/cgi-wrap/WEBunwrap"><IMG SRC="/BFROOT/www/Images/unwrap3.gif" WIDTH=112 HEIGHT=20 ALT="Unwrap page!" VSPACE=0></A> </TD></TR>
</TABLE>  
</TD> 
</TR>
<TR> 
<TD BGCOLOR="#000000"> 
  <TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=118 SUMMARY="Side Navigation Bar">
  <TR BGCOLOR="#C0D9D9"><TD WIDTH=118 ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Physics_search.html">Phys. Search</A></TD></TR>		
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/who.htm">Who's who?</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Physics_meetings.html">Meetings</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/old-www/Physics/">Archive</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=center bgcolor="#FFFFFF"><STRONG>Physics analysis</STRONG></TD></TR>
<TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/WednesdayMeetings/index.html">Physics Mtgs</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Analysis/An_princ.txt">Principles</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/doc/PhysBook/physBook.html">Physics Book</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/doc/workbook/workbook.html">Workbook</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/BaBarData/BaBarData.html">BaBar Data</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/skims/skims.html">Skims</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Computing/Offline/Kanga/index.html">Kanga</A><small> &amp; </small><A HREF="/BFROOT/www/Computing/Offline/ROOT/index.html">Root</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Tools/Scripts/intro.html">Scripts</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/PhysicsReleases/index.html">Physics Releases</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=center bgcolor="#FFFFFF"><STRONG>Physics Groups</STRONG></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Analysis/AWG/">BaBar <strong>AWG</strong>s</A></TD></TR>
<!--
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Physics/Analysis/slrare/slrare.html">Semileptonic/<br>Rad. penguin</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Analysis/Hadronic_B_and_C/index.html">Hadronic B&amp;C</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Analysis/tauqed/">Tau QED</A></TD></TR>
-->
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=center bgcolor="#FFFFFF"><STRONG><A HREF="/BFROOT/www/Physics/Tools/tools.html">Tools Groups</A></STRONG></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Analysis/Statistics/">Statistics WG</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Tools/generators/">Evt generators</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Tools/Pid/pid.html">Particle ID</A></TD></TR>
 <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Tools/Vertex/vertexforum.html">Vertexing &amp;<br>Composition</A></TD></TR>
 <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/Physics/Tools/Tagging/Main/index.html">B-tagging</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Computing/Offline/Beta/Beta.html">Beta</A><small> &amp; </small><A HREF="/BFROOT/www/Physics/Tools/BetaTools/BetaTools.html">BetaTools</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=center bgcolor="#FFFFFF"><STRONG>Pubs &amp; Notes</STRONG></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><a href="https://oraweb.slac.stanford.edu:8080/pls/slac/babar_documents.startup">Publications DB</a></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="http://www.slac.stanford.edu/babar-internal/BAD/doc/index.html"><strong>B.A.D.</strong> notes</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A href="/BFROOT/www/doc/Analysis/index.html"><strong>B.A.D.</strong> system</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="https://oraweb.slac.stanford.edu:8080/pls/slacquery/babar_documents.startup">Public Plots</A></TD></TR>
  <TR BGCOLOR="#C0D9D9"><TD ALIGN=LEFT BGCOLOR="#C0D9D9"><A HREF="/BFROOT/www/Organization/PubBoard/index.html">Publications Bd.</A></TD></TR>
  </TABLE>
 </TD>
 </TR>
 </TABLE>

<TABLE WIDTH=118 BORDER=0 CELLPADDING=0 CELLSPACING=2 SUMMARY="unwrap">
<TR><TD WIDTH=118>
  <TABLE WIDTH=118 BORDER=0 CELLPADDING=0 CELLSPACING=0 SUMMARY="Notification table">
  <TR BGCOLOR="wheat"><TD WIDTH="118"><CENTER><font size="-1">Check this page for HTML 4.01 Transitional compliance with the<br>
  <A HREF="http://validator.w3.org/check/referer?doctype=HTML+4.01+Transitional">W3C Validator</A></font>
  </CENTER></TD></TR>
  <TR BGCOLOR="wheat"><TD WIDTH="118"><CENTER>
  <a href="http://validator.w3.org/"><font size="-1">(More checks...)</font></a>
  </CENTER></TD></TR>
  </TABLE>
</TD></TR>
</TABLE>

 </TD> <!-- End Left Strip -->
<!--STARTINDEX--> 
 <TD WIDTH="100%" VALIGN=TOP ALIGN=LEFT BGCOLOR="#FFFFFF">
 <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=8 SUMMARY="Information content"> 
 <!-- FOLLOWING <TR><TD> IS END OF HEADER FILE, NEEDS TWO </TD></TR></TABLE> -->
 <TR><TD>
